[tool.poetry]
name = "isro-project"
version = "0.1.0"
description = ""
authors = ["pupperemeritus <5bdiposan@relay.firefox.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
plotly = "^5.22.0"
geopandas = "^1.0.0"
pandas = "^2.2.2"
openpyxl = "^3.1.5"
pyarrow = "^16.1.0"
scipy = "^1.14.0"
polars = "^1.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
